name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: leebadagyumin0129/velog-copy
          stage: main
          yaml: |
            name: velog-copy-server
            app: python@3.12
            options:
              ports: "8000"
              start: uvicorn main:app --host=0.0.0.0
              env:
                - name: DB_ADRESS
                  value: ${{ secrets.DB_ADRESS }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
              buildenv: []
              install: pip install fastapi uvicorn pymysql python-multipart pillow
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}